GET http://localhost:3000/utilisateurs/1 

###
GET http://localhost:3000/exercises/1
###
GET http://localhost:3000/lessons/1

###

POST http://localhost:3000/gen/applications/1/lessons/1/exercises/1 HTTP/1.1
Content-Type: application/json

{
"variations": {
     "group": "third"
 }
}

###

GET http://localhost:3000/gen/applications/1/lessons/2/exercises/3 HTTP/1.1
